### ISSUE TITLE
Automate beta bot deployments off `develop`

### ISSUE THREAD

**Issue by samcat116** [NachoMemes/NachoMemes#24]
A deployment of the beta bot should be run every time there is a merge into develop.

**Comment by samcat116** [comment]
Here will be the deployment steps

1. Deployments get run on pushes to develop or master for staging and production respectively. I've already made the changes to the `config.yml` file to support this [here](https://github.com/cooperpellaton/NachoMemes/commit/a53b672730580368dc7945ccdfb073dce8d60061). 
2. Run terraform apply to ensure the infrastructure is in place. Remember to output the IP of the host to be used in later steps
3. Run an Ansible script on the host to checkout and run `docker compose up`

**Comment by ironchefpython** [comment]
![image](https://user-images.githubusercontent.com/859398/66622098-79b42300-ebb4-11e9-9419-25008fd55701.png)

**Comment by ironchefpython** [comment]
fixed in #93
