### ISSUE TITLE
Relicensing to defend against Amazon freeloading

### ISSUE THREAD

**Issue by ironchefpython** [NachoMemes/NachoMemes#99]
I think we all agree that we don't want Amazon to do to memebots what they did to Elasticsearch.  As a precaution, we should relicense this project to defend against predatory action by AWS.   Please suggest an appropriate license in the comments below.

**Comment by coreysabia** [comment]
I am suggesting we use an appropriate license.

**Comment by ironchefpython** [comment]
> I am suggesting we use an appropriate license.

I am suggesting you make an appropriate contribution.

**Comment by coreysabia** [comment]
A copyleft GNU Affero General Public License is probably the best way to go.

**Comment by ironchefpython** [comment]
> A copyleft GNU Affero General Public License is probably the best way to go.

I'm not 100% sure that will require AWS to obtain a commercial license from us before offering Nachomemes as a hosted service in direct competition with us.

**Comment by coreysabia** [comment]
What was this closed, no decision was made.

**Comment by coreysabia** [comment]
I am reopening this.

**Comment by coreysabia** [comment]
Yeah. That doesn't stop me. This issue has not been resolved. Do not keep closing it.
